### ISSUE TITLE
Imports not recognized after adding a dependency in `Package.swift` 

### ISSUE THREAD

**Issue by MaxDesiatov** [apple/sourcekit-lsp#967] opened 2023-11-10 20:21 UTC
# Steps to reproduce

1. Add a new dependency to a target in `Package.swift`, e.g. `.product(name: "ServiceLifecycle", package: "swift-service-lifecycle")` from `.package(url: "https://github.com/swift-server/swift-service-lifecycle.git", from: "2.3.0")`.
2. Open any `.swift` file from a target that had the new dependency added.
3. Import the new dependency: `import ServiceLifecycle`

# Expected result

`import ServiceLifecycle` is a valid statement that brings symbols from this dependency into scope.

# Actual result

`import ServiceLifecycle` is reported as erroneous with a confusing error message: `could not build Objective-C module 'ServiceLifecycle: sourcekitd`, even though it has no Objective-C code. Symbols from this imported module are not recognized as valid. Restarting VS Code doesn't fix the error.

**Comment by ahoppen** [comment] 2023-11-10 20:41
Tracked in Apple’s issue tracker as rdar://118247030

**Comment by ahoppen** [comment] 2023-11-13 18:02
This is a dupe of https://github.com/apple/swift-package-manager/issues/5925.

You need to build so that a `.swiftmodule` gets added for the new dependency that sourcekit-lsp can pick up.

**Closed by ahoppen** 2023-11-13 18:02 UTC
Labels: bug
