### ISSUE TITLE
Better initializer completion 

### ISSUE THREAD

**Issue by dabrahams** [apple/sourcekit-lsp#1027] opened 2024-01-17 21:17 UTC
When I type `SomeType(` I would like very much to get a completion list for `SomeType` initializers.  Possibly I'm missing something, but there doesn't seem to be any way to get such a list unless I type “`SomeType.init`” (and even that seems a bit unreliable).  Then I have to go back and delete “`.init`” which is a pain.

**Comment by ahoppen** [comment] 2024-01-17 21:34
Tracked in Apple’s issue tracker as rdar://121144822

**Comment by ahoppen** [comment] 2024-02-20 17:45
I just tried reproducing this and the following produces initializer completions for me in the following tests case, both with the Swift 5.9 release and a recent main development snapshot. 

```swift
struct Foo {
  init(x: Int) {}
}
func test() {
  Foo(<complete here>
}
```

I am able to get initializer completions inside the SourceKit-LSP code base as well, so it also appears to be working across modules and in more complex scenarios.

Do you have a project that reproduces the issue or am I missing something?

**Comment by ahoppen** [comment] 2024-04-16 17:56
Closing this because it does seem to work for me. Feel free to open if you are continuing to see issues with it and have a reproducing example.

**Closed by ahoppen** 2024-04-16 17:56 UTC
