### ISSUE TITLE
sourcekitd: cannot find 'Utilities' in scope

### ISSUE THREAD

**Issue by dimaportenko** [apple/sourcekit-lsp#851] opened 2023-10-03 20:02 UTC
I'm trying to use `sourcekit-lsp` in the neovim and get following error. 
```
sourcekitd: cannot find 'Utilities' in scope
```
where Utilities is class from Utilities.swift in the same folder. Not sure what I'm doing wrong. It's working just fine in the Xcode.

<img width="1508" alt="CleanShot 2023-10-03 at 22 56 12@2x" src="https://github.com/apple/sourcekit-lsp/assets/6594232/7c201394-cbe5-4515-b15d-9c0fbd784872">         

The project source code is https://github.com/dimaportenko/CapsLockStatus

**Comment by ahoppen** [comment] 2023-10-03 20:08
Tracked in Apple’s issue tracker as rdar://116417127

**Comment by ahoppen** [comment] 2023-10-04 17:08
Based on your screenshot it looks like you are trying to open an Xcode project with sourcekit-lsp, is that correct? #730 tracks this.

To summarize: sourcekit-lsp does not have support for Xcode projects thus opens every file with fallback compiler arguments, i.e. in a single file mode that doesn’t see any of the other files.

**Comment by dimaportenko** [comment] 2023-10-04 17:18
@ahoppen thank you for the information.

**Comment by ahoppen** [comment] 2023-10-04 17:21
Closing the issue as a duplicate of https://github.com/apple/sourcekit-lsp/issues/730.

**Comment by wojciech-kulik** [comment] 2023-10-04 17:21
@dimaportenko you can make it work with nvim. Check out my question: https://github.com/apple/sourcekit-lsp/issues/818 :). Use the tool mentioned there.

**Closed by ahoppen** 2023-10-04 17:21 UTC

**Comment by dimaportenko** [comment] 2023-10-04 17:25
@wojciech-kulik thank you, I'll try it out next time I have time.
